services:
  app:
    build: ./app
    container_name: flask_app
    expose:
      - "5000"
    command: python app.py

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/self-signed.crt:/etc/ssl/certs/server.crt:ro
      - ./nginx/self-signed.key:/etc/ssl/private/server.key:ro
    depends_on:
      - app